accounts/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^login/$', views.AccountLoginView.as_view(), name='login'),
    url(r'^logout/$', views.AccountLogoutView.as_view(), name='logout'),
    url(r'^register/$', views.AccountRegisterView.as_view(), name='register'),
    url(r'^profile/$', views.AccountProfileView.as_view(), name='detail'),
    url(r'^profile/edit$', views.AccountProfileEditView.as_view(), name='update'),

]

blogs/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^create$', BlogCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[\w-]+)$', BlogDetailView.as_view(), name='detail'),
    url(r'^(?P<blog_pk>[\w-]+)/post/(?P<pk>[\w-]+)$', PostDetailView.as_view(), name='post-detail'),
    url(r'^(?P<blog_pk>[\w-]+)/create$', PostCreateView.as_view(), name='post-create'),
]

wordtag/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib import admin


from blogs.views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/site.css' %}">
  {% block stylesheets %}{% endblock %}
</head>
<body>
  <h1>Wordtag!</h1>
  <div id="navigation">
    <ul>
      {% if user.is_authenticated %}
      <li> Hello {{ user.username }}!</li>
      {% if user.profile.photo %}
      <li><img width="75px" src="{{ user.profile.photo.url }}" alt="you" /></li>
      {% endif %}
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'accounts:login' %}">Login</a></li>
      <li><a href="{% url 'accounts:register' %}">Register</a></li>
      {% endif %}
    </ul>
  </div>
  <div>
    {% block content %}{% endblock %}
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="{% static 'js/site.js' %}"></script>
  {% block scripts %}{% endblock %}
</body>
</html>